apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-deployments
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: forwarder
        image: wwblodge1/forwarder:latest
      - name: logger
        image: wwblodge1/logger:latest
      - name: cam
        image: wwblodge1/cam:v1
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0