apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: processor
        image: wwblodge1/processor:latest

